# 2.2 Variable 变量

In [15]:
import torch
from torch.autograd import Variable

In [16]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable= Variable(tensor, requires_grad=True)#torch使用tensor来计算的

In [17]:
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [18]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)

In [19]:
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [20]:
v_out.backward()
# v_out = 1/4*sum(var*var)
# d(v_out)/d(var) = 1/4*2*variable = variable/2
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [21]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [22]:
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
